import type {
  ProductRecommendationCategory,
  ProductRecommendationRecord,
} from "@/lib/types";

export type RecommendationCategory = {
  key: ProductRecommendationCategory;
  label: string;
  accentClass: string;
};

export const recommendationCategories: RecommendationCategory[] = [
  {
    key: "videogames",
    label: "Videogames",
    accentClass: "bg-[var(--color-blue)]",
  },
  {
    key: "perifericos",
    label: "Perifericos",
    accentClass: "bg-[var(--color-purple)]",
  },
  {
    key: "acessorios",
    label: "Acessorios",
    accentClass: "bg-[var(--color-pink)]",
  },
];

const seedDate = "2026-04-04T00:00:00.000Z";

export const seedProductRecommendations: ProductRecommendationRecord[] = [
  {
    id: "switch-oled",
    slug: "nintendo-switch-oled",
    name: "Nintendo Switch OLED",
    category: "videogames",
    context: "Bom quando eu quero couch co-op rapido, biblioteca forte e algo facil de levar da mesa para a sala.",
    imageUrl: "/recommendations/switch-oled.svg",
    href: "https://www.nintendo.com/us/store/products/nintendo-switch-oled-model-white-set/",
    storeLabel: "Nintendo",
    linkKind: "external",
    isActive: true,
    sortOrder: 10,
    createdAt: seedDate,
    updatedAt: seedDate,
  },
  {
    id: "ps5-slim",
    slug: "playstation-5-slim",
    name: "PlayStation 5 Slim",
    category: "videogames",
    context: "Faz sentido quando eu quero algo mais premium no sofa, com desempenho estavel e catalogo forte para campanha.",
    imageUrl: "/recommendations/ps5-slim.svg",
    href: "https://direct.playstation.com/en-us/buy-consoles/playstation5-console-model-group-slim",
    storeLabel: "PlayStation",
    linkKind: "external",
    isActive: true,
    sortOrder: 20,
    createdAt: seedDate,
    updatedAt: seedDate,
  },
  {
    id: "8bitdo-ultimate",
    slug: "8bitdo-ultimate-bluetooth-controller",
    name: "8BitDo Ultimate Bluetooth Controller",
    category: "perifericos",
    context: "Controle confortavel para Switch e PC, com dock que deixa tudo carregado sem eu precisar lembrar de cabo.",
    imageUrl: "/recommendations/8bitdo-ultimate.svg",
    href: "https://www.8bitdo.com/ultimate-bluetooth-controller/",
    storeLabel: "8BitDo",
    linkKind: "external",
    isActive: true,
    sortOrder: 30,
    createdAt: seedDate,
    updatedAt: seedDate,
  },
  {
    id: "wave-3",
    slug: "elgato-wave-3",
    name: "Elgato Wave:3",
    category: "perifericos",
    context: "Microfone simples de acertar, com audio limpo e software pratico para separar fontes durante a live.",
    imageUrl: "/recommendations/wave-3.svg",
    href: "https://www.elgato.com/us/en/p/wave-3",
    storeLabel: "Elgato",
    linkKind: "external",
    isActive: true,
    sortOrder: 40,
    createdAt: seedDate,
    updatedAt: seedDate,
  },
  {
    id: "cloud-3-wireless",
    slug: "hyperx-cloud-iii-wireless",
    name: "HyperX Cloud III Wireless",
    category: "perifericos",
    context: "Headset confortavel para sessoes longas, com som consistente e voz clara quando eu preciso abrir call.",
    imageUrl: "/recommendations/cloud-3-wireless.svg",
    href: "https://hyperx.com/products/hyperx-cloud-iii-wireless-gaming-headset",
    storeLabel: "HyperX",
    linkKind: "external",
    isActive: true,
    sortOrder: 50,
    createdAt: seedDate,
    updatedAt: seedDate,
  },
  {
    id: "stream-deck-mk2",
    slug: "elgato-stream-deck-mk2",
    name: "Elgato Stream Deck MK.2",
    category: "acessorios",
    context: "Atalho fisico para cenas, efeitos e comandos, sem me obrigar a sair do jogo toda hora.",
    imageUrl: "/recommendations/stream-deck-mk2.svg",
    href: "https://www.elgato.com/us/en/p/stream-deck-mk-2-black",
    storeLabel: "Elgato",
    linkKind: "external",
    isActive: true,
    sortOrder: 60,
    createdAt: seedDate,
    updatedAt: seedDate,
  },
  {
    id: "ugreen-dock",
    slug: "ugreen-revodok-usb-c-hub",
    name: "UGREEN Revodok USB-C Hub",
    category: "acessorios",
    context: "Resolve porta, captura e energia em um ponto so, o que ajuda muito quando o setup comeca a crescer.",
    imageUrl: "/recommendations/ugreen-dock.svg",
    href: "https://www.ugreen.com/collections/usb-c-hub",
    storeLabel: "UGREEN",
    linkKind: "external",
    isActive: true,
    sortOrder: 70,
    createdAt: seedDate,
    updatedAt: seedDate,
  },
  {
    id: "litra-glow",
    slug: "logitech-litra-glow",
    name: "Logitech Litra Glow",
    category: "acessorios",
    context: "Luz pequena e facil de posicionar para melhorar camera sem comer metade da bancada.",
    imageUrl: "/recommendations/litra-glow.svg",
    href: "https://www.logitechg.com/en-us/products/lighting/litra-glow.946-000001.html",
    storeLabel: "Logitech G",
    linkKind: "external",
    isActive: true,
    sortOrder: 80,
    createdAt: seedDate,
    updatedAt: seedDate,
  },
];
